### ISSUE TITLE
[track] Release `subxt` to crates.io

### ISSUE THREAD

**Issue by dvdplm** [paritytech/subxt#345]
Tracking ticket to release `subxt` as a crate on crates.io.

Things we want in:

- [x] https://github.com/paritytech/subxt/issues/391 (Possible bug preventing anything other than DefaultConfig being used) #409 
- [x] https://github.com/paritytech/subxt/issues/405
- [x] https://github.com/paritytech/subxt/issues/187
- [ ] https://github.com/paritytech/subxt/issues/390 (I think that it would be good to do this tidy up prior to a release)
- [x] https://github.com/paritytech/subxt/issues/328 https://github.com/paritytech/subxt/pull/352
- [x] https://github.com/paritytech/subxt/issues/411
- [ ] https://github.com/paritytech/subxt/issues/313 (investigate)
- [ ] https://github.com/paritytech/subxt/issues/309 (TODO: split up into single issues)
- [x] https://github.com/paritytech/subxt/pull/375 (and resolve issue with mismatching `DispatchError` #394)
- [x] https://github.com/paritytech/subxt/issues/331 https://github.com/paritytech/subxt/pull/373
- [x] https://github.com/paritytech/subxt/issues/334 (Not "done" but we have nightly runs now to test compatibility against latest)
- [x] https://github.com/paritytech/subxt/issues/316 https://github.com/paritytech/subxt/pull/349
- [x] https://github.com/paritytech/subxt/issues/312

**Known blockers**

- [ ] git dependencies

Closes #339 

Nice-to-haves, work for future releases:
- [x] https://github.com/paritytech/subxt/issues/315
- [ ] https://github.com/paritytech/subxt/issues/206
- [ ] https://github.com/paritytech/subxt/issues/272
- [ ] https://github.com/paritytech/subxt/issues/393

**Comment by jsdw** [comment]
Note: add a deprecation notice to `substrate-subxt` 0.15 on crates.io when we release `subxt` 0.16
