### ISSUE TITLE
[tracking] Release 0.18

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#420]
- [x] https://github.com/paritytech/subxt/issues/456 (Required for the release).
- [x] ~~https://github.com/paritytech/subxt/issues/406 (Large; It may be that the next release just splits the client out to pave way for a new dynamic-focused crate in a 0.18; let's see how it shapes up!)~~ let's not try to get this in; it's probably a slightly longer term thing.
- [ ] https://github.com/paritytech/subxt/issues/416 (Large; requires work in substrate)
- [x] https://github.com/paritytech/subxt/issues/413 (Moderate; breaking change)
- [ ] https://github.com/paritytech/subxt/issues/187 (Fairly minor I think?)
- [x] https://github.com/paritytech/subxt/issues/411 (Minor; small breaking change)
- [ ] https://github.com/paritytech/subxt/issues/390 (Minor; breaking change to clarify these struct APIs)
- [x] https://github.com/paritytech/subxt/issues/414 (Minor; no breaking changes)
- [ ] https://github.com/paritytech/subxt/issues/419 (Minor; no breaking changes)
- [ ] https://github.com/paritytech/subxt/issues/351 (Minor; no breaking changes)
- [x] https://github.com/paritytech/subxt/issues/422 (Minor)
- [x] https://github.com/paritytech/subxt/issues/443 (Minor; no breaking changes)

Nice to haves carries over from last release:

- [x] https://github.com/paritytech/subxt/issues/315
- [ ] https://github.com/paritytech/subxt/issues/206
- [ ] https://github.com/paritytech/subxt/issues/272
- [ ] https://github.com/paritytech/subxt/issues/393

Other thoughts:

- https://github.com/paritytech/subxt/issues/398 would be nice to make some progress on, even if just settling on an approach (let's see how the discussion goes in that issue before we nail it down to a particular release)

**Comment by jsdw** [comment]
Released; See #470 for the next release.
