### ISSUE TITLE
Write a guide and redo examples

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#898]
- Write a guide which covers getting set up to use Subxt and then each of the major areas
- Revamp all examples; all examples will be included as part of the guide.

We'll aim to cover some of the other doc issues we have open in the guide (I'll close them since we will address them as part of this):

- [x] #811
- [x] #612 (we generally want to just document the macro usage nicely)
- [ ] #611 (this is a good "general" example use case)
- [ ] #728 (OfflineClient example)
- [ ] #393 (some sort of FAQ or guide for common issues is probably a good idea!)
- [ ] #367 (a good note to document that Tokio is likely required if jsonrpsee is used)
- [x] #258 (We'll cover this; building and submitting extrinsics)
